version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - llm-network

  llm-rust:
    build: .
    container_name: llm-rust-service
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
      - RUST_LOG=info
    networks:
      - llm-network

volumes:
  ollama_data:

networks:
  llm-network:
    driver: bridge
